# Generated by Django 4.0.5 on 2022-06-28 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alarmas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('foto', models.CharField(max_length=9999999)),
                ('tipo', models.CharField(max_length=60)),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Camaras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('foto', models.CharField(max_length=9999999)),
                ('definicion', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cercos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('foto', models.CharField(max_length=9999999)),
                ('voltaje', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
            ],
        ),
    ]
